### ISSUE TITLE
Icon offset horizontally with left or right-side panel

### ISSUE THREAD

**Issue by RoboRay** [RaphaelRochet/circular-battery-indicator#3]
Thank you so much for bringing this feature back to life!

However, I found a display issue when moving the panel to the left or right side of the monitor with Dash to Panel...  the battery icon stacks to the left of the other system status indicators.  Please see an example here: https://i.imgur.com/JBFFCrY.png

**Comment by RaphaelRochet** [comment]
Yup, pretty ugly ^^"

This is caused by the fact that my indicator here is a drawing, not an actual icon, and thought it does not follow global styling.

Open the stylesheet.css file and try to fiddle with the margin : 
````css
/* 0 px top and bottom, 4 pixels left and right /*
.circular-battery-indicator {
	margin: 0 4px;
}
````
Change it like this to be able to set different margins for left and right :
````css
.circular-battery-indicator {
	/* Order is Top - Right - Bottom - Left */
	margin: 0 4px 0 1px;
}
````
